### ISSUE TITLE
Conda error message during Galaxy restart

### ISSUE THREAD

**Issue by hackdna** [galaxyproject/cloudman#62]
I've launched a cluster based on `cloudman-dev` bucket, added a few items to `job_conf.xml` and restarted Galaxy using the Admin console. Galaxy appears to work fine but I've noticed the following message in the `main.log`:

```
galaxy.tools.deps DEBUG 2016-10-28 16:48:39,575 Unable to find config file './dependency_resolvers_conf.xml'
/bin/sh: 1: Syntax error: Unterminated quoted string
galaxy.tools.deps.resolvers.conda WARNING 2016-10-28 16:48:39,581 Conda installation requested and failed.
/bin/sh: 1: Syntax error: Unterminated quoted string
galaxy.tools.deps.resolvers.conda WARNING 2016-10-28 16:48:39,586 Conda installation requested and failed.
galaxy.tools.search DEBUG 2016-10-28 16:48:39,626 Starting to build toolbox index.
docutils WARNING 2016-10-28 16:48:39,925 <string>:38: (ERROR/3) Document may not end with a transition.

docutils WARNING 2016-10-28 16:48:40,815 <string>:61: (ERROR/3) Document may not end with a transition.

docutils WARNING 2016-10-28 16:48:42,493 <string>:35: (ERROR/3) Document may not end with a transition.

docutils WARNING 2016-10-28 16:48:42,965 <string>:16: (ERROR/3) Unexpected indentation.

docutils WARNING 2016-10-28 16:48:43,335 <string>:22: (ERROR/3) Document may not end with a transition.

docutils WARNING 2016-10-28 16:48:43,346 <string>:30: (WARNING/2) Duplicate explicit target name: "krona".

docutils WARNING 2016-10-28 16:48:43,347 <string>:4: (ERROR/3) Duplicate target name, cannot be used as a unique reference: "krona".

docutils WARNING 2016-10-28 16:48:43,348 <string>:28: (ERROR/3) Duplicate target name, cannot be used as a unique reference: "krona".

docutils WARNING 2016-10-28 16:48:43,443 <string>:16: (ERROR/3) Document may not end with a transition.

docutils WARNING 2016-10-28 16:48:43,574 <string>:50: (ERROR/3) Document may not end with a transition.

galaxy.tools.search DEBUG 2016-10-28 16:48:44,360 Toolbox index finished. It took: 0:00:04.734109
```

I'm not sure if this is of any consequence.

**Comment by afgane** [comment]
I found a problem with a least a couple of lines you mention here and the fix will require a new version of the galaxy file system archive, which I'm likely to build today to integrate some of the other changes that need to be incorporated.

**Comment by afgane** [comment]
There's a new flavor for the 16.10 image: `Dev 10.31`, which is today's build with fixes for the above errors.

**Comment by hackdna** [comment]
Thanks. I've just tried starting a new cluster using image 16.10 and flavor Dev 10/31 but I'm now getting the following errors in the cluster info log:
```
21:09:26 - Initializing 'Galaxy' cluster type with storage type 'volume'. Please wait...
21:09:36 - Completed the initial cluster startup process. Configuring a predefined cluster of type Galaxy.
21:09:41 - Adding volume vol-0c99f9b65244e8e18 (galaxyIndices FS)...
21:10:05 - Mount point /cvmfs/data.galaxyproject.org already exists and is not empty!? (['byhand', 'managed']) Will attempt to mount volume vol-0c99f9b65244e8e18
21:10:08 - STATUS CHECK: Exception checking status of FS 'galaxyIndices': too many values to unpack
21:10:09 - Supervisor service prerequisites OK; starting the service.
21:10:10 - Adding volume vol-0990726ac4cf50567 (galaxy FS)...
21:10:27 - Extracting archive url http://s3.amazonaws.com/cloudman/fs-archives/galaxyFS-20161031.tar.gz to /mnt/galaxy. This could take a while...
21:12:48 - Migration service prerequisites OK; starting the service.
21:12:53 - STATUS CHECK: Exception checking status of FS 'galaxyIndices': too many values to unpack
21:12:53 - Postgres service prerequisites OK; starting the service.
21:12:55 - ProFTPd service prerequisites OK; starting the service.
21:12:55 - Slurmctld service prerequisites OK; starting the service.
21:13:02 - Slurmd service prerequisites OK; starting the service.
21:13:08 - STATUS CHECK: Exception checking status of FS 'galaxyIndices': too many values to unpack
21:13:19 - STATUS CHECK: Exception checking status of FS 'galaxyIndices': too many values to unpack
21:13:31 - STATUS CHECK: Exception checking status of FS 'galaxyIndices': too many values to unpack
21:13:46 - STATUS CHECK: Exception checking status of FS 'galaxyIndices': too many values to unpack
21:14:02 - STATUS CHECK: Exception checking status of FS 'galaxyIndices': too many values to unpack
21:14:18 - STATUS CHECK: Exception checking status of FS 'galaxyIndices': too many values to unpack
```
The last message is repeating continuously. There is a new 200GB volume named galaxyIndicesFS in the AWS web console (in addition to the regular 200GB Galaxy volume and 30GB root volume). Service status: Applications orange, Data red.

**Comment by afgane** [comment]
Sorry, I copied an old flavor config that hadn't been updated for the recent changes. Should be fixed now.

**Comment by hackdna** [comment]
No problem, the cluster started successfully this time but I still see similar log messages when restarting Galaxy:
```
galaxy.tools.search DEBUG 2016-10-31 21:52:03,004 Starting to build toolbox index.
docutils WARNING 2016-10-31 21:52:03,330 <string>:38: (ERROR/3) Document may not end with a transition.

docutils WARNING 2016-10-31 21:52:04,262 <string>:61: (ERROR/3) Document may not end with a transition.

docutils WARNING 2016-10-31 21:52:05,961 <string>:35: (ERROR/3) Document may not end with a transition.

docutils WARNING 2016-10-31 21:52:06,447 <string>:16: (ERROR/3) Unexpected indentation.

docutils WARNING 2016-10-31 21:52:06,824 <string>:22: (ERROR/3) Document may not end with a transition.

docutils WARNING 2016-10-31 21:52:06,836 <string>:30: (WARNING/2) Duplicate explicit target name: "krona".

docutils WARNING 2016-10-31 21:52:06,838 <string>:4: (ERROR/3) Duplicate target name, cannot be used as a unique reference: "krona".

docutils WARNING 2016-10-31 21:52:06,838 <string>:28: (ERROR/3) Duplicate target name, cannot be used as a unique reference: "krona".

docutils WARNING 2016-10-31 21:52:06,934 <string>:16: (ERROR/3) Document may not end with a transition.

docutils WARNING 2016-10-31 21:52:07,066 <string>:50: (ERROR/3) Document may not end with a transition.

galaxy.tools.search DEBUG 2016-10-31 21:52:07,894 Toolbox index finished. It took: 0:00:04.889849
```
Cluster info log:
```
21:36:15 - Initializing 'Galaxy' cluster type with storage type 'volume'. Please wait...
21:36:21 - Completed the initial cluster startup process. Configuring a predefined cluster of type Galaxy.
21:36:33 - Supervisor service prerequisites OK; starting the service.
21:36:35 - Adding volume vol-057f6a7eea75cbf5e (galaxy FS)...
21:36:53 - Extracting archive url http://s3.amazonaws.com/cloudman/fs-archives/galaxyFS-20161031.tar.gz to /mnt/galaxy. This could take a while...
21:39:09 - Migration service prerequisites OK; starting the service.
21:39:15 - Postgres service prerequisites OK; starting the service.
21:39:16 - ProFTPd service prerequisites OK; starting the service.
21:39:17 - Slurmctld service prerequisites OK; starting the service.
21:39:20 - Galaxy service prerequisites OK; starting the service.
21:39:28 - Slurmd service prerequisites OK; starting the service.
21:39:51 - Galaxy service state changed from 'Starting' to 'Running'
21:39:51 - GalaxyReports service prerequisites OK; starting the service.
21:40:05 - All cluster services started; the cluster is ready for use.
21:51:35 - Removing 'Galaxy' service
21:51:35 - Removing 'GalaxyReports' service
21:51:35 - Shutting down Galaxy Reports...
21:51:38 - Shutting down Galaxy...
21:51:47 - Galaxy service prerequisites OK; starting the service.
21:52:12 - Galaxy service state changed from 'Starting' to 'Running'
```

**Comment by afgane** [comment]
I saw those but don't know where they are coming from but don't feel they actually affect anything (they're warnings). @jmchilton or @davebx - would you have any comments on where to go look to fix these?

**Comment by mvdbeek** [comment]
Those are warnings from tools (looks like krona is the guilty one) that have issues with RST formatting of the help text.

**Comment by hackdna** [comment]
Thanks, I'm fine with closing this if it's a non-issue.
